name: 'Terraform Apply'

on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        description: "Select which module to deploy"
        options: 
        - module-1
        - module-2
        required: true

permissions: write-all

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.5

    - name: Verify AWS credentials
      run: aws sts get-caller-identity

    - name: Set Account ID
      id: account
      run: |
        echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

    - name: Check previous AWSGoat Deployment
      id: check
      run: |
        echo "${{ env.ACCOUNT_ID }}"
        aws s3api head-object --bucket do-not-delete-awsgoat-state-files-${{ env.ACCOUNT_ID }} --key terraform.tfstate
      continue-on-error: true

    - name: Exit if previous deployment exists
      if: steps.check.outcome == 'success'
      run: |
        echo "A Previous AWSGoat deployment exists, run the Terraform Destroy Action"
        exit 1

    - name: Terraform Init
      run: |
        cd modules/${{ github.event.inputs.module }}
        terraform init

    - uses: actions/setup-python@v5
      with:
        python-version: 3

    - name: install
      run: |
        pip install boto3

    - name: Terraform Plan
      id: plan
      run: |
        cd modules/${{ github.event.inputs.module }}
        terraform plan -input=false

    - name: Terraform Apply
      run: |
        cd modules/${{ github.event.inputs.module }}
