name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        description: "Select which module to destroy"
        options:
        - module-1
        - module-2
        required: true

permissions: write-all

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: |
          cd modules/${{ github.event.inputs.module }}
          terraform init

      - name: Terraform Destroy
        run: |
          cd modules/${{ github.event.inputs.module }}
          terraform destroy -auto-approve -input=false

      # opzionale: elimina il marker nello stesso bucket se lo usi solo come "lock"
      - name: Delete state marker from S3 (optional)
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws s3 rm s3://do-not-delete-awsgoat-state-files-${ACCOUNT_ID}/terraform.tfstate || true
